# Multilingual NER Model Fine-Tuning

This notebook handles the fine-tuning of the XLM-RoBERTa model using the interleaved Hungarian, English, and German datasets.

## Environment Setup

Initializing hardware settings and loading core libraries for training.

In [21]:
import os
from dotenv import load_dotenv
import torch
import evaluate
import wandb
import numpy as np
from datasets import load_from_disk
from transformers import(
    AutoTokenizer,
    AutoModelForTokenClassification,
    DataCollatorForTokenClassification,
    TrainingArguments,
    Trainer,
    EarlyStoppingCallback,
    pipeline
)
from transformers.utils.notebook import NotebookProgressCallback 
from huggingface_hub import notebook_login

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

load_dotenv()

cuda

True

## Weights & Biases Logging

Connecting to W&B to track metrics during the experiment runs.

In [2]:
wandb.login()

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from WANDB_API_KEY.
wandb: Currently logged in as: rchrdhlzhfr (rchrdhlzhfr-personal) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

## Loading Processed Datasets

Loading the tokenized and aligned datasets.

In [3]:
# Load interleaved and gold-only datasets
interleaved_dataset = load_from_disk("../data/processed/harmonized_dataset/interleaved_dataset")
tokenized_dataset = load_from_disk("../data/processed/tokenized_dataset/tokenized_dataset")

gold_only_dataset = load_from_disk("../data/processed/harmonized_dataset/gold_only_dataset")
gold_only_tokenized_dataset = load_from_disk("../data/processed/tokenized_dataset/gold_only_tokenized_dataset")

# Load individual language datasets (harmonized)
hun_dataset = load_from_disk("../data/processed/harmonized_dataset/hun_dataset")
eng_dataset = load_from_disk("../data/processed/harmonized_dataset/eng_dataset")
ger_dataset = load_from_disk("../data/processed/harmonized_dataset/ger_dataset")

# Load individual language datasets (tokenized)
tokenized_hun_dataset = load_from_disk("../data/processed/tokenized_dataset/hun_tokenized_dataset")
tokenized_eng_dataset = load_from_disk("../data/processed/tokenized_dataset/eng_tokenized_dataset")
tokenized_ger_dataset = load_from_disk("../data/processed/tokenized_dataset/ger_tokenized_dataset")

## Tokenizer, model and data collator initialization

In [4]:
model_id = "xlm-roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_id)
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

Preparing dictionaries for model initialization on interleaved dataset

In [5]:
label_names = interleaved_dataset['train']['ner'].features.feature.names
label_names

['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC', 'B-MISC', 'I-MISC']

In [6]:
id2label = {i: label for i, label in enumerate(label_names)}
label2id = {v: k for k, v in id2label.items()}

In [7]:
model = AutoModelForTokenClassification.from_pretrained(
    model_id,
    id2label=id2label,
    label2id=label2id,
)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForTokenClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
lm_head.bias                | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
roberta.pooler.dense.weight | UNEXPECTED |
classifier.bias             | MISSING    |
classifier.weight           | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

### Data Collator Verification

Ensuring labels are correctly padded and aligned within batches.

In [8]:
# Lengths of the first three labels before data collator
[print(len(tokenized_dataset['train']['labels'][i])) for i in range(3)];

60
87
20

In [9]:
example_batch = data_collator([tokenized_dataset["train"][i] for i in range(3)])
example_batch["labels"]

tensor([[-100,    0,    7, -100, -100,    8, -100, -100,    0,    0,    0, -100,
            0,    7, -100,    0,    0,    0, -100,    0, -100,    0,    0, -100,
            0, -100, -100,    0,    0,    0, -100,    0,    0, -100, -100,    0,
            0, -100, -100,    0,    0, -100,    0, -100,    0,    0, -100, -100,
         -100,    0,    0, -100, -100,    0,    0, -100, -100,    0, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100],
        [-100,    1, -100, -100,    0,    0, -100, -100, -100, -100, -100, -100,
            0,    0, -100, -100, -100, -100, -100, -100,    0,    0,    0,    0,
            0,    0,    0,    0,    0, -100,    0,    0, -100,    0,    0,    0,
            0,    0,    0, -100, -100, -100, -100,    0, -100,    0,    0,    0,
            0,    0,    0,    0, -100,    0,    0, -100,    0, -100,    0, -100,
         -100,    0, -100,    0,    0, -100,    0, -100,    0, -100, -100,    0,
         -100,    0, -100,    0,    0, -100,    0, -100,    0,    0, -100, -100,
            0, -100, -100],
        [-100,    0,    0,    0,    0,    0, -100, -100,    0,    0,    0, -100,
            0,    0,    0, -100, -100,    0, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100,
         -100, -100, -100]])

Inspecting the first three labels after data collator

In [10]:
# Lengths of the first three labels after data collator
[print(len(example_batch['labels'][i])) for i in range(3)];

87
87
87

## Evaluation Metrics

Defining the `compute_metrics` function using `seqeval` to calculate Precision, Recall, and F1 score for all entity tags.

In [11]:
metric = evaluate.load("seqeval")

In [13]:
def compute_metrics(eval_preds, label_names):
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)

    # Remove ignored index (special tokens) and convert to labels
    true_labels = [[label_names[l] for l in label if l != -100] for label in labels]
    true_predictions = [
        [label_names[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    all_metrics = metric.compute(predictions=true_predictions, references=true_labels)
    results = {
        "overall_precision": all_metrics["overall_precision"],
        "overall_recall": all_metrics["overall_recall"],
        "overall_f1": all_metrics["overall_f1"],
        "overall_accuracy": all_metrics["overall_accuracy"],
    }

    for k, v in all_metrics.items():
        if k not in ["overall_precision", "overall_recall", "overall_f1", "overall_accuracy"]:
            results[f"{k}_f1"] = v["f1"]
            results[f"{k}_precision"] = v["precision"]
            results[f"{k}_recall"] = v["recall"]
    
    return results

## Training Configuration

Setting hyper-parameters such as learning rate, batch size, and weight decay.

In [14]:
# Login to HuggingFace
notebook_login()

In [15]:
args = TrainingArguments(
    output_dir="../xlm-roberta-ner-hun_eng_ger",
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    metric_for_best_model="eval_combined_loss",
    load_best_model_at_end=True,
    greater_is_better=False,
    per_device_train_batch_size=96,
    per_device_eval_batch_size=192,
    bf16=True,
    bf16_full_eval=True,
    dataloader_num_workers=8,
    dataloader_persistent_workers=True,
    dataloader_prefetch_factor=2,
    learning_rate=1e-5,
    num_train_epochs=5,
    lr_scheduler_type="cosine",
    weight_decay=0.01,
    warmup_ratio=0.1,
    push_to_hub=False,
    report_to="wandb",
    run_name="ner_exp_hun_eng_ger"
)

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

## Trainer Setup & Training

Starting the training process with the Hugging Face `Trainer`.

In [16]:
eval_datasets = {
    "combined": tokenized_dataset["validation"],
    "hun": tokenized_hun_dataset["validation"],
    "eng": tokenized_eng_dataset["validation"],
    "ger": tokenized_ger_dataset["validation"]
}

In [17]:
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=eval_datasets,
    data_collator=data_collator,
    compute_metrics=lambda x: compute_metrics(x, label_names=label_names),
    processing_class=tokenizer,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

In [18]:
wandb.init(
    entity="rchrdhlzhfr-personal",
    project="polyglot-ner-project",
    name="hun_eng_ger_training"
    )

trainer.train()

wandb.finish()

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

## Final Test Set Evaluation

Performing a comprehensive evaluation across separate Hungarian, English, and German test sets to assess cross-lingual generalization.

In [19]:
test_datasets = {
    "combined": tokenized_dataset["test"],
    "test_hun": tokenized_hun_dataset["test"],
    "test_eng": tokenized_eng_dataset["test"],
    "test_ger": tokenized_ger_dataset["test"]
}

In [22]:
# Disabling all multiprocessing features for stable evaluation
trainer.args.dataloader_num_workers = 0 
trainer.args.dataloader_persistent_workers = False
trainer.args.dataloader_prefetch_factor = None

# Fix 'on_train_begin' error by removing notebook callback
trainer.remove_callback(NotebookProgressCallback)

wandb.init(
    entity="rchrdhlzhfr-personal",
    project="polyglot-ner-project",
    name="hun_eng_ger_test"
    )
trainer.args.dataloader_num_workers = 0 
trainer.args.dataloader_persistent_workers = False
trainer.args.dataloader_prefetch_factor = None

test_results = trainer.evaluate(eval_dataset=test_datasets)

wandb.finish()

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

#### Inspecting testing results

Charts in Weights&Biases are clearly showing that the model performs significantly worse on the English dataset in all types of labels.

In [23]:
test_results.keys()

dict_keys(['eval_combined_loss', 'eval_combined_overall_precision', 'eval_combined_overall_recall', 'eval_combined_overall_f1', 'eval_combined_overall_accuracy', 'eval_combined_LOC_f1', 'eval_combined_LOC_precision', 'eval_combined_LOC_recall', 'eval_combined_MISC_f1', 'eval_combined_MISC_precision', 'eval_combined_MISC_recall', 'eval_combined_ORG_f1', 'eval_combined_ORG_precision', 'eval_combined_ORG_recall', 'eval_combined_PER_f1', 'eval_combined_PER_precision', 'eval_combined_PER_recall', 'eval_combined_runtime', 'eval_combined_samples_per_second', 'eval_combined_steps_per_second', 'epoch', 'eval_test_hun_loss', 'eval_test_hun_overall_precision', 'eval_test_hun_overall_recall', 'eval_test_hun_overall_f1', 'eval_test_hun_overall_accuracy', 'eval_test_hun_LOC_f1', 'eval_test_hun_LOC_precision', 'eval_test_hun_LOC_recall', 'eval_test_hun_MISC_f1', 'eval_test_hun_MISC_precision', 'eval_test_hun_MISC_recall', 'eval_test_hun_ORG_f1', 'eval_test_hun_ORG_precision', 'eval_test_hun_ORG_recall', 'eval_test_hun_PER_f1', 'eval_test_hun_PER_precision', 'eval_test_hun_PER_recall', 'eval_test_hun_runtime', 'eval_test_hun_samples_per_second', 'eval_test_hun_steps_per_second', 'eval_test_eng_loss', 'eval_test_eng_overall_precision', 'eval_test_eng_overall_recall', 'eval_test_eng_overall_f1', 'eval_test_eng_overall_accuracy', 'eval_test_eng_LOC_f1', 'eval_test_eng_LOC_precision', 'eval_test_eng_LOC_recall', 'eval_test_eng_MISC_f1', 'eval_test_eng_MISC_precision', 'eval_test_eng_MISC_recall', 'eval_test_eng_ORG_f1', 'eval_test_eng_ORG_precision', 'eval_test_eng_ORG_recall', 'eval_test_eng_PER_f1', 'eval_test_eng_PER_precision', 'eval_test_eng_PER_recall', 'eval_test_eng_runtime', 'eval_test_eng_samples_per_second', 'eval_test_eng_steps_per_second', 'eval_test_ger_loss', 'eval_test_ger_overall_precision', 'eval_test_ger_overall_recall', 'eval_test_ger_overall_f1', 'eval_test_ger_overall_accuracy', 'eval_test_ger_LOC_f1', 'eval_test_ger_LOC_precision', 'eval_test_ger_LOC_recall', 'eval_test_ger_MISC_f1', 'eval_test_ger_MISC_precision', 'eval_test_ger_MISC_recall', 'eval_test_ger_ORG_f1', 'eval_test_ger_ORG_precision', 'eval_test_ger_ORG_recall', 'eval_test_ger_PER_f1', 'eval_test_ger_PER_precision', 'eval_test_ger_PER_recall', 'eval_test_ger_runtime', 'eval_test_ger_samples_per_second', 'eval_test_ger_steps_per_second'])

In [24]:
# Most important metrics
print(f"Overall F1 score:               {test_results["eval_combined_overall_f1"]*100:.2f}%")
print(f"F1 score on Hungarian dataset:  {test_results["eval_test_hun_overall_f1"]*100:.2f}%")
print(f"F1 score on English dataset:    {test_results["eval_test_eng_overall_f1"]*100:.2f}%")
print(f"F1 score on German dataset:     {test_results["eval_test_ger_overall_f1"]*100:.2f}%")

Overall F1 score:               80.51%
F1 score on Hungarian dataset:  96.29%
F1 score on English dataset:    59.44%
F1 score on German dataset:     85.27%

Labels per category in the English dataset

In [25]:
print(f"F1 score on PER labels:     {test_results["eval_test_eng_PER_f1"]*100:.2f}%")
print(f"F1 score on LOC labels:     {test_results["eval_test_eng_LOC_f1"]*100:.2f}%")
print(f"F1 score on ORG labels:     {test_results["eval_test_eng_ORG_f1"]*100:.2f}%")
print(f"F1 score on MISC labels:    {test_results["eval_test_eng_MISC_f1"]*100:.2f}%")

F1 score on PER labels:     74.81%
F1 score on LOC labels:     47.07%
F1 score on ORG labels:     23.33%
F1 score on MISC labels:    0.00%

Since the English dataset performance on all labels is weak, we might suspect that it acts as noise in the model. This is could be attributed to its quality (silver).

The performance on the English dataset is so weak, that is doesn't worth spending time on other possible label-mappings, we should rather focus on defining clear boundaries for Hungarian and German language for the model by training it on the other two datasets.

## Fine tuning on Gold-only dataset

Creating labels from gold_only dataset for compute metrics function

In [26]:
gold_only_label_names = gold_only_dataset['train']['ner'].features.feature.names

In [27]:
gold_only_label_names

['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC', 'B-MISC', 'I-MISC']

In [28]:
args = TrainingArguments(
    output_dir="../xlm-roberta-ner-hun_ger",
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    metric_for_best_model="eval_combined_loss",
    load_best_model_at_end=True,
    greater_is_better=False,
    per_device_train_batch_size=96,
    per_device_eval_batch_size=192,
    bf16=True,
    bf16_full_eval=True,
    dataloader_num_workers=8,
    dataloader_persistent_workers=True,
    dataloader_prefetch_factor=2,
    learning_rate=1e-5,
    num_train_epochs=5,
    lr_scheduler_type="cosine",
    weight_decay=0.01,
    warmup_ratio=0.1,
    push_to_hub=False,
    report_to="wandb",
    run_name="ner_exp_hun_ger"
)

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

In [29]:
eval_datasets = {
    "combined": gold_only_tokenized_dataset["validation"],
    "hun": tokenized_hun_dataset["validation"],
    "ger": tokenized_ger_dataset["validation"]
}

In [30]:
trainer = Trainer(
    model=model,
    args=args,
    train_dataset=gold_only_tokenized_dataset["train"],
    eval_dataset=eval_datasets,
    data_collator=data_collator,
    compute_metrics=lambda x: compute_metrics(x, label_names=gold_only_label_names),
    processing_class=tokenizer,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

In [31]:
wandb.init(
    entity="rchrdhlzhfr-personal",
    project="polyglot-ner-project",
    name="hun_ger_training"
    )

trainer.train()

wandb.finish()

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

In [32]:
test_datasets = {
    "combined": gold_only_tokenized_dataset["test"],
    "test_hun": tokenized_hun_dataset["test"],
    "test_ger": tokenized_ger_dataset["test"]
}

In [33]:
# Disabling all multiprocessing features for stable evaluation
trainer.args.dataloader_num_workers = 0 
trainer.args.dataloader_persistent_workers = False
trainer.args.dataloader_prefetch_factor = None

# Fix 'on_train_begin' error by removing notebook callback
trainer.remove_callback(NotebookProgressCallback)

wandb.init(
    entity="rchrdhlzhfr-personal",
    project="polyglot-ner-project",
    name="hun_ger_test"
    )
trainer.args.dataloader_num_workers = 0 
trainer.args.dataloader_persistent_workers = False
trainer.args.dataloader_prefetch_factor = None

test_results = trainer.evaluate(eval_dataset=test_datasets)

wandb.finish()

early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled
d:\Projects\polyglot_ner_project\.venv\Lib\site-packages\seqeval\metrics\v1.py:57: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
early stopping required metric_for_best_model, but did not find eval_combined_loss so early stopping is disabled

## Inspecting testing results on gold-only datasets

In [35]:
# Most important metrics
print(f"Overall F1 score:               {test_results["eval_combined_overall_f1"]*100:.2f}%")
print(f"F1 score on Hungarian dataset:  {test_results["eval_test_hun_overall_f1"]*100:.2f}%")
print(f"F1 score on German dataset:     {test_results["eval_test_ger_overall_f1"]*100:.2f}%")

Overall F1 score:               89.75%
F1 score on Hungarian dataset:  96.47%
F1 score on German dataset:     85.64%

Labels per category in the Hungarian dataset

In [37]:
# Hungarian
print(f"F1 score on PER labels:     {test_results["eval_test_hun_PER_f1"]*100:.2f}%")
print(f"F1 score on LOC labels:     {test_results["eval_test_hun_LOC_f1"]*100:.2f}%")
print(f"F1 score on ORG labels:     {test_results["eval_test_hun_ORG_f1"]*100:.2f}%")
print(f"F1 score on MISC labels:    {test_results["eval_test_hun_MISC_f1"]*100:.2f}%")

F1 score on PER labels:     96.55%
F1 score on LOC labels:     95.67%
F1 score on ORG labels:     98.40%
F1 score on MISC labels:    85.49%

Labels per category in the German dataset

In [38]:
# German
print(f"F1 score on PER labels:     {test_results["eval_test_ger_PER_f1"]*100:.2f}%")
print(f"F1 score on LOC labels:     {test_results["eval_test_ger_LOC_f1"]*100:.2f}%")
print(f"F1 score on ORG labels:     {test_results["eval_test_ger_ORG_f1"]*100:.2f}%")
print(f"F1 score on MISC labels:    {test_results["eval_test_ger_MISC_f1"]*100:.2f}%")

F1 score on PER labels:     90.33%
F1 score on LOC labels:     87.83%
F1 score on ORG labels:     76.83%
F1 score on MISC labels:    0.00%

By removing the English dataset we could prove that the model (xlm-roberta-base) is fully capable of learning the task, yielding ~96% on Hungarian and ~85% on German language.

If we include the English dataset, the end users will experience terrible performance on English text. This destroys trust in the model. So I would recommend sending the Hun-Ger NER model to production and getting a better quality English dataset to be able to get decent performance (85+%) on all languages.

## Saving the model and pushing to HuggingFace Hub

In [39]:
# Creating folder if it does not exist

os.makedirs("../models", exist_ok=True)

save_directory = "../models/xlm-roberta-ner-hun_ger"
# Saving the model
trainer.save_model(save_directory)

# Saving the tokenizer
tokenizer.save_pretrained(save_directory)

print(f"Model and tokenizer successfully saved to {save_directory}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Model and tokenizer successfully saved to ../models/xlm-roberta-ner-hun_ger

In [41]:
# Pushing model to HuggingFace Hub
trainer.push_to_hub()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Processing Files (0 / 0): |          |  0.00B /  0.00B

New Data Upload: |          |  0.00B /  0.00B

CommitInfo(commit_url='https://huggingface.co/RichardHolzhofer/xlm-roberta-ner-hun_ger/commit/c16c42f2557d81099ad835a3ea913ac6b0d7f69e', commit_message='End of training', commit_description='', oid='c16c42f2557d81099ad835a3ea913ac6b0d7f69e', pr_url=None, repo_url=RepoUrl('https://huggingface.co/RichardHolzhofer/xlm-roberta-ner-hun_ger', endpoint='https://huggingface.co', repo_type='model', repo_id='RichardHolzhofer/xlm-roberta-ner-hun_ger'), pr_revision=None, pr_num=None)

## Inferencing with the model via HuggingFace Hub

In [45]:
ner_pipeline = pipeline(
    "ner",
    model="RichardHolzhofer/xlm-roberta-ner-hun_ger",
    aggregation_strategy="simple"
    )

# Hungarian Example
# Translation: "János Kovács visited the OTP Bank headquarters in Budapest yesterday."
hun_text = "Kovács János tegnap az OTP Bank központjában, Budapesten járt."

print("--- Hungarian Prediction ---")
for entity in ner_pipeline(hun_text):
    print(f"Word: {entity['word']:<15} | Label: {entity['entity_group']:<5} | Score: {entity['score']:.4f}")
print("\n" + "="*50 + "\n")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

--- Hungarian Prediction ---
Word: Kovács János    | Label: PER   | Score: 0.9959
Word: OTP Bank        | Label: ORG   | Score: 0.9765
Word: Budapesten      | Label: LOC   | Score: 0.9962

==================================================

In [46]:
# German Example
# Translation: "Angela Merkel visited the BMW headquarters in Munich yesterday."
ger_text = "Angela Merkel besuchte gestern die Zentrale von BMW in München."
print("--- German Prediction ---")
for entity in ner_pipeline(ger_text):
    print(f"Word: {entity['word']:<15} | Label: {entity['entity_group']:<5} | Score: {entity['score']:.4f}")

--- German Prediction ---
Word: Angela Merkel   | Label: PER   | Score: 0.9913
Word: BMW             | Label: ORG   | Score: 0.9971
Word: München         | Label: LOC   | Score: 0.9968